Update feature
Ali-0111/vet_clinic pull request #2
Opened 2023-07-12 13:21 UTC by Ali-0111

-Transaction started by : ( BEGIN TRANSACTION; )
![image](https://github.com/Ali-0111/vet_clinic/assets/73581663/0b1bd824-1137-4c45-8c5a-5876ddf7e4be)

- Inside Transaction update applied and verified usind SELECT * FROM:
![image](https://github.com/Ali-0111/vet_clinic/assets/73581663/6b35dcb6-82ad-4999-be79-bf304a338f26)

2023-07-12 17:51 UTC, mckent05 requested changes
Hi @Ali-0111, 

# STATUS: CHANGES REQUIRED ♻️ ♻️ 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![almost there](https://user-images.githubusercontent.com/73607512/207265056-d056ea78-77c5-4b66-802e-694a5ed4ecf3.gif)

## Highlights
- All linter checks are passing ✔️ ✔️ 
- Your PR is professional 👍 👍 
- Good job updating your animals table 👏 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-12 17:51 UTC, mckent05 commented on data.sql
> +('Ditto', '2022-05-14', 22, true, 4 );
- Good job done so far, but you seem to have switched values for the weights and escape attempt attributes, please make sure you properly and carefully input data as given in the [project requirements](https://github.com/microverseinc/curriculum-databases/blob/main/db-structure/vet_clinic_query_update_tables.md) 👍 👍

2023-07-12 17:51 UTC, mckent05 commented on data.sql
> +('Squirtle', '1993-04-2', 3, false, 12.13);
- Good job done so far, but the weights for `Charmander`, `Plantmon`, `Squirtle`, and `Angemon`, please fix this so you could have the right query result 👍 👍

2023-07-12 17:51 UTC, mckent05 commented on queries.sql
> +COMMIT;
- After correcting the data in your `data.sql` file, please re-run the transaction below again, as I noticed you skipped some in your file 🙏 
Inside a transaction:
- Delete all animals born after Jan 1st, 2022.
- Create a savepoint for the transaction.
- Update all animals' weight to be their weight multiplied by -1.
- Rollback to the savepoint
- Update all animals' weights that are negative to be their weight multiplied by -1.
- Commit transaction

2023-07-12 17:51 UTC, mckent05 commented on queries.sql
> +SELECT AVG(weight_kg) AS Weight_Average  FROM animals;
- Please re-run this query and attach the right results in your PR after correcting the data in your `data.sql` file. Please fix this 👍 👍

2023-07-12 17:51 UTC, mckent05 commented on queries.sql
> +WHERE escape_attempts = (SELECT MAX(escape_attempts) FROM animals);
- this is a wrong query, to get the animal that has escaped the most, neutered or non-neutered, please use the query below:
   `SELECT neutered, AVG(escape_attempts) FROM animals
   GROUP BY neutered`

2023-07-12 17:51 UTC, mckent05 commented on queries.sql
> +
- Please re-run this query and attach the right results in your PR after correcting the data in your data.sql file. Please fix this 👍 👍
- Also, I cannot see the query for this query, `What is the average number of escape attempts per animal type of those born between 1990 and 2000?` in your query file, though I see you have included the results in your PR. Please fix this 🙏 
- Also, the attached result for the above-mentioned query is not correct, to get the `average number of escape attempts per animal type of those born between 1990 and 2000?`. Please use this query:
```sql
SELECT species, AVG(escape_attempts) FROM animals
   GROUP BY species
   WHERE  date_of_birth >= '1990/01/01' AND date_of_birth <= '2000/12/31'
```

2023-07-13 15:07 UTC, Ali-0111 commented
@ CR, 
- I inserted the value again, and re run the queries again.

2023-07-13 15:25 UTC, divinecharlotte approved these changes
# Hello @Ali-0111      😃 🥳 🎉 🎈 

Great Job 😄 👏 You've done it. Your project is complete!  There is nothing else to say  👍🏻 ✅ 
### To Highlight 💯


- Good implementation of the required changes👍 
- Your PR is professional 👍 👍
 




## Congratulations! 🎉 

<img src="https://media3.giphy.com/media/3KC2jD2QcBOSc/giphy.gif"/>

Cheers, and Happy coding!👏👏👏


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-13 17:26 UTC, Ali-0111 commented
Thanks for the review.

2023-07-13 17:26 UTC, merged